name: Danger Kotlin Image
on: workflow_dispatch

jobs:
  danger-kotlin:
    name: Publish Danger Kotlin image
    strategy:
      matrix:
        version: [ '2.7', '3.0' ]
    uses: ./.github/workflows/publish-image.yml
    with:
      image-name: danger-kotlin
      title: Danger Kotlin image
      tags: |
        ${{ matrix.version }}
        ${{ matrix.version }}-{{date 'YYYYMMDD'}}
      build-args: version=${{ matrix.version }}
