name: Publish Docker image

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Image base name'
        required: true
        type: string
      context:
        description: 'Location of build files'
        required: true
        type: string
      title:
        description: 'Human-readable image title'
        required: true
        type: string
      tags:
        description: 'Image tags separated with linebreak'
        required: true
        type: string
      build-args:
        description: 'List of build-time variables separated with linebreak'
        required: false
        type: string

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/redmadrobot/android/${{ inputs.image-name }}
          tags: ${{ inputs.tags }}
          labels: |
            org.opencontainers.image.title=${{ inputs.title }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          push: false
          build-args: ${{ inputs.build-args }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
