name: Ruby Image
on: workflow_dispatch

jobs:
  ruby:
    name: Publish Ruby image
    strategy:
      matrix:
        version: [ '2.7', '3.0' ]
    uses: ./.github/workflows/publish-image.yml
    with:
      image-name: ruby
      context: ruby
      title: Ruby image
      tags: ${{ matrix.version }}
      build-args: version=${{ matrix.version }}
