name: Ruby Image
on: workflow_dispatch

jobs:
  ruby:
    name: Publish Ruby image
    strategy:
      matrix:
        version: [ '3.1', '3.2', '3.3' ]
    uses: ./.github/workflows/publish-image.yml
    with:
      image-name: ruby
      context: ruby
      platforms: linux/amd64
      title: Ruby image
      tags: |
        ${{ matrix.version }}
        ${{ matrix.version }}-{{date 'YYYYMMDD'}}
        type=raw,value=latest,enable=${{ matrix.version == '3.3' }}
      build-args: version=${{ matrix.version }}
