name: Ruby Image
on: workflow_dispatch

jobs:
  ruby:
    name: Publish Ruby image
    strategy:
      matrix:
        version: [ '2.7', '3.0', '3.1', '3.2' ]
    uses: ./.github/workflows/publish-image.yml
    with:
      image-name: ruby
      context: ruby
      title: Ruby image
      tags: |
        type=raw,value=${{ matrix.version }}
        type=raw,value=latest,enable=${{ matrix.version == '3.2' }}
      build-args: version=${{ matrix.version }}
